### ISSUE TITLE
draggable-points and bar charts

### ISSUE THREAD

**Issue by ghUserNme** [highslide-software/draggable-points#18] opened 2015-01-21 09:10 UTC
Hi

If I click on a point in a bar chart the values are reduced, is there a work-around for this, or are bar charts not supported?

I've reproduced the error here:
http://jsfiddle.net/jsfUserName/s4vp4peL/18/

**Comment by pawelfus** [comment] 2015-06-17 14:10
Duplicate of #16.

**Closed by pawelfus** 2015-06-17 14:10 UTC
